@startuml
title DS02 – Enregistrer une vente

actor Employe
participant UI
participant CaisseService
participant StockService
participant VenteRepository
participant TransactionManager

Employe -> UI : Enregistrer vente
UI -> CaisseService : enregistrerVente(listeProduits)
CaisseService -> TransactionManager : begin()
CaisseService -> StockService : reserverStock(produits)
CaisseService -> VenteRepository : save(vente)
CaisseService -> TransactionManager : commit()
CaisseService --> UI : Confirmation vente
UI --> Employe : Affiche total et confirmation
@enduml
